### ISSUE TITLE
Checker for materialized view

### ISSUE THREAD

**Issue by ifirmawan** [akvo/Akvo-ResponseGrouper#16]
## Todo/Done

Evaluate the query on materialize view with the following steps:
- [x] Get results from a query before executing it as a materialized view.
- [x] Create results from a query as a data frame.
- [x] Group by data frame by: name (Sanitation, Water, etc) and data point to get the amount of duplication.
